import "./globals.css";
import "../lib/fontawesome";

export const metadata = {
  title: "Travlprep",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
